sudo: required
services:
  - docker

before_install:
  - docker build -t marco1022/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run marco1022/react-test npm run test -- --coverage

after_success:
  - docker build -t marco1022/multi-client ./client
  - docker build -t marco1022/multi-nginx ./nginx
  - docker build -t marco1022/multi-server ./server
  - docker build -t marco1022/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  - docker push marco1022/multi-client
  - docker push marco1022/multi-nginx
  - docker push marco1022/multi-server
  - docker push marco1022/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-654842437587
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_Access_key
  secret_access_key:
    secure: #AWS_Secret_access_key
